slidewiki/slidewiki-platform

- actions/activityfeed/contentdiscussion/loadContentDiscussion.js
- actions/activityfeed/loadActivities.js
- actions/datasource/loadDataSource.js
- actions/datasource/loadDataSourceCount.js
- actions/loadContent.js
- actions/loadContentHistory.js
- actions/loadContentModules.js
- actions/loadContentQuestions.js
- actions/loadContentUsage.js
- actions/loadContributors.js
- actions/loadDeck.js
- actions/loadDeckEdit.js
- actions/loadDeckView.js
- actions/loadSimilarContents.js
- actions/loadTranslations.js
- actions/slide/loadSlideEdit.js
- actions/slide/loadSlideView.js
As needed by Marios, adding support for dash in deck id and slide id for revision support in URL.
> Swik 407 supporting dash in sid param

- actions/loadDeck.js
This adds support for dash in spath.
> Fixes SWIK-412, adding support for dash in spath

- actions/loadDeckEdit.js
- actions/slide/loadSlideEdit.js
- actions/slide/saveSlide.js
- components/Deck/ContentPanel/SlideModes/SlideEditPanel/SlideContentEditor.js
- components/Deck/TreePanel/TreeNode.js
- services/slide.js
- allow escape key on > 1 levels in the tree
- forward to view mode after editing the slide
> Improve deck editor actions

- components/AddDeck/AddDeck.js
addDeck redirect should happen in the action not component
> ode refactoring

- components/Login/LoginModal.js
- services/user.js
Front-end login component is slightly modified  to use email-password combination since user service now accepts this combination for login. Previously it was username-password.
> SWIK-243 Using email (instead of username) and pass for login

- components/Import/Import.js
Changed just one line of code. Corrected base64 encoding of the file, in order to safely ship it across a network.
> SWIK-111 base64 encode selected file

- stores/ContentModulesStore.js
Small change: Comment count is now updated when a user creates a new comment/reply.
> SWIK-498 Added comment count updating

- components/AddDeck/AddDeck.js
Changed AddDeck.js to improved layout of the form and fix accessibility issue on form labels.
> SWIK-530 updated form labels for a11y and improved design based on user feedback

- components/Login/LoginModal.js
https://slidewiki.atlassian.net/browse/SWIK-410
> SWIK-410 modal bug

- components/Deck/ContentPanel/SlideModes/SlideEditPanel/SlideContentEditor.js
- components/DefaultHTMLLayout.js
Reverts slidewiki/slidewiki-platform#70
> Revert "SWIK-537 Reposition (drag) absolute elements from PPTX2HTML import"

- components/Deck/ContentPanel/SlideModes/SlideEditPanel/SlideContentEditor.js
- components/DefaultHTMLLayout.js
Also addresses SWIK-489 - Create border around divs in edit mode for
clearly showing draggable elements
> SWIK 537 Reposition (drag) absolute elements from PPTX2HTML import

- components/DefaultHTMLLayout.js
Added JIRA feedback button html to DefaultHTMLLayout.js
> added feedback button

- components/Deck/ContentPanel/SlideModes/SlideEditPanel/SlideContentEditor.js
Small fix to remove green dotted edit border before saving slide
> SWIK 540 - Small fix to remove green dotted edit border before saving slide

- plugins/UserStorage/userStoragePlugin.js
Added reloading of page when user is deleted (in plugin userContext)
> SWIK-493_refresh_page_after_logout

- stores/ActivityFeedStore.js
New activity is now added to the activity feed when a new comment/reply is added.
> Swik 572 update activity feed

- components/Deck/ActivityFeedPanel/ActivityList.js
got error “TypeError: this.refs.activityList is undefined[Learn More]”
> SWIK 550  Make slide content fit in slide view and edit component

- components/Login/LoginModal.js
I have added code to allow the modal will close when users press esc. 
In order to show the modal, press the button "Sign In" placed at the top left of the heder of the page.
> SWIK-458: now esc close the modal

- components/Deck/ActivityFeedPanel/ActivityList.js
Reverts slidewiki/slidewiki-platform#99
> Revert "SWIK-550 - this.refs.activityList does seem to work."

- components/AddDeck/AddDeck.js
Added descriptions to license dropdown, removed cancel button and tags. Updated text on page.
Still needs:
- language dropdown to be populated
- improved form validation, in particular terms and conditions checkbox which users are missing
- terms and condition link
- improve upload form SWIK-567
> Updated Add deck page for SWIK 561 to 566

- actions/loadAddDeck.js
- actions/user/toggleLoginModal.js
- actions/user/userSignIn.js
- components/Login/LoginModal.js
- stores/UserProfileStore.js
Replaced react modal with semantic-ui modal
It is not accessible but there is no more overlapping anymore
I also made it simpler to toggle the login modal
> Swik-514 semanticui modal

- components/Error/BadGateway.js
- components/Error/BadRequest.js
- components/Error/Forbidden.js
- components/Error/GatewayTimeout.js
- components/Error/InternalServerError.js
- components/Error/MethodNotAllowed.js
- components/Error/NotFound.js
- components/Error/NotImplemented.js
- components/Error/PayloadTooLarge.js
- components/Error/RequestHeaderTooLarge.js
- components/Error/ServiceUnavailable.js
- components/Error/TooManyRequests.js
- components/Error/URITooLong.js
- components/Error/Unauthorized.js
- components/Error/UnprocessableEntity.js
Removed "X" icon from error pages.
> Fix SWIK-618. Removing cross 'X' button from error pages

- components/Deck/ContentModulesPanel/ContentDiscussionPanel/Comment.js
- components/Deck/ContentModulesPanel/ContentDiscussionPanel/ContentDiscussionPanel.js
Just a couple of changes to enable automatic reply title and message when there are no comments.
> SWIK-642 Automatic reply title and 'No comments' message

- components/Login/LoginModal.js
> SWIK-641_reopening_loginModal on right conditions

- components/User/UserProfile/UserSettings.js
- components/User/UserRegistration/UserRegistration.js
I exchanged dimmers in user registration and user settings
> Swik-640 same modals

- components/Login/LoginModal.js
- components/User/UserProfile/AccountDeletion.js
Changed jquery selector and one line in LoginModal
> Swik-647 login modal lifetime

- components/Deck/ContentPanel/DeckModes/DeckEditPanel/DeckPropertiesEditor.js
Removed tag field from deck editor.
> Swik 484 implement deck edit component

- actions/user/userprofile/fetchUser.js
I have to assist to test it, because I need to delete a user in the database, after someone has logged in.
> SWIK-658 Prevent continuous user querying

- components/User/UserProfile/ChangePassword.js
- components/User/UserRegistration/UserRegistration.js
> Changed the regex to match 8 characters or more

- components/Login/LoginModal.js
React-modal is not imported now. Also, Modal is not called in the componentDidMount() method.
In order to test, access to the login modal clicking the sign-up button
> SWIK-677-fix react-modal removed completely removed

- components/AddDeck/AddDeck.js
- components/Footer/Footer.js
- components/Home/DataProtection.js
- components/Home/Imprint.js
- configs/routes.js
- added NavLinks to Footer component for Imprint and Data Protection Statement
- added Imprint and DataProtecetion component to components/Home/ 
- Updated NavLink on 'Add Deck' page, now pointing to 'Imprint'
Todo: Adding Terms of Use page. Waiting for definite text from Fraunhofer.
> Swik 532 legal information

- actions/user/userprofile/removeUser.js
- components/Login/HeaderDropdown.js
- components/Thumbnail/Thumbnail.js
- components/User/UserProfile/DeckCard.js
- components/User/UserProfile/PopularDecks.js
- components/User/UserProfile/PublicUserData.js
- components/User/UserProfile/UserProfile.js
- services/userProfile.js
Deleted tabs in my profile view
used thumbnail component in DeckCard
> Swik-675 remaking user profile page

- components/Home/Home.js
Updated the content of the home page to include the new layout and hard coded decks for the "featured decks".
@DaryaTarasowa I couldn't get your branch for 499 to run locally so this does not include your changes.
> Swik 499 update home page

- components/Deck/ContentPanel/DeckModes/DeckViewPanel/DeckViewPanel.js
user in deck view has been linked to user profile.
> SWIK-689, connecting deck view user (i.e. deck creator) to his profile

- components/User/UserProfile/AccountDeletion.js
- components/User/UserProfile/UserSettings.js
Remarks:
-     The other services are not aware of this! When using the frontend this is no problem.
-     Just login, deleteUser, getUser, getPublicUser handling this attribute. I think for the trial this is enough.
-     A user could be re-activated if someone access the database. There is no API for this
> SWIK-692_delete_user_to_deactivate_user] 

- components/Deck/ContentPanel/SlideModes/SlideEditPanel/SlideContentEditor.js
- services/slide.js
+removed new slide template from services/slide.js because it did not
work
> SWIK-685  hide input box for relative slides in slide content editor

- components/Deck/ContentModulesPanel/ContentDiscussionPanel/ContentDiscussionPanel.js
Reverts slidewiki/slidewiki-platform#150
> Revert "SWIK-642 Added notifications for empty comment fields"

- components/Home/DeckList.js
> Swik 499 homepage

- assets/ckeditor_config.js
- components/Deck/ContentPanel/SlideModes/SlideEditPanel/SlideContentEditor.js
- custom_modules/ckeditor/config.js
Need to test of domain / same origin policy works on server
> SWIK-349_Implement_image_upload_in_slide_content_editor_CKEditor

- components/AddDeck/AddDeck.js
- components/Deck/ContentPanel/DeckModes/DeckEditPanel/DeckPropertiesEditor.js
- components/Deck/ContentPanel/DeckModes/DeckViewPanel/DeckViewPanel.js
- components/Home/DeckList.js
- stores/SearchParamsStore.js
See https://slidewiki.atlassian.net/browse/SWIK-702
> SWIK 559  Add languages of pilot participants (Spanish, Italian, etc ) in add deck component

- components/Deck/ContentPanel/ContentActions/ContentActionsFooter.js
in adddeck this.props.ContentStore.selector.id is 0
> Fix pdfHref for AddDeck typeerror

- components/AddDeck/AddDeck.js
- services/deck.js
Just a minor change to deck.js which solves this bug.
> SWIK-703 Fixing AddDeck 500-'undefined id' bug

- actions/user/userSignOut.js
- components/Login/HeaderDropdown.js
- components/User/UserProfile/ChangePersonalData.js
- components/User/UserProfile/UserProfile.js
- components/common/LanguageDropdown.js
Please test the header dropdown on all pages that are reachable from it (even trigger a page refresh on these pages before using the dropdown)
> SWIK-691 Fix header dropdown

- plugins/UserStorage/userStoragePlugin.js
> Swik-681 cookie for only one domain

- components/AddDeck/AddDeck.js
- components/common/LanguageDropdown.js
Elaborated common/languagedropdown. used it in AddDeck
> SWIK-457_language_dropdown_in_addeck

- configs/general.js
- docker-compose.yml
Made API key for user service an environment variable
> SWIK-737_APIkey_as_environmentvariable

- components/Login/LoginModal.js
It was detected than the form wasn't sent when users pressed ENTER, and also, it showed some error.
I have detected that the submit button was moved outside the form in some of our previous changes of style. Now it is inside the form and when user press enter, the submit action is triggered without error.
> Swik704-fix

- components/User/UserProfile/PopularDecks.js
- components/User/UserProfile/PrivatePublicUserProfile.js
- components/User/UserProfile/UserProfile.js
- services/userProfile.js
Added a sort button to the "My Decks" page.
> SWIK-764 Sort my decks

- components/Deck/ContentPanel/SlideModes/SlideEditPanel/SlideContentEditor.js
- components/Import/Import.js
- custom_modules/ckeditor/config.js
SWIK 750 and 630   source code editor and special characters message in import screen
> SWIK 750 and 630   source code editor and special characters message in import screen

- custom_modules/ckeditor/config.js
Testing at http://localhost:3000/deck/7-2/slide/105-11/105-11:3
> Improved extraplugin calling

- components/Deck/ContentPanel/DeckModes/DeckViewPanel/DeckViewPanel.js
- components/Deck/ContentPanel/SlideModes/SlideViewPanel/SlideViewPanel.js
- components/Home/DeckList.js
Added “comments outline” icon In Decklist and deckview
> SWIK-721 - Add one single generic flag/icon

- components/User/UserProfile/DeckCard.js
- components/User/UserProfile/PopularDecks.js
Fixed URL creation for thumbnails in users decks view
> SWIK-769_thumbnails_not_shown

- components/Header/Header.js
- components/Header/SearchBox.js
@Sole-Valero  has fixed accessibility issues in the header. I've checked and all ok
> SWIK-759: label for searching box added. alt attribute for logo added

- components/Deck/ContentModulesPanel/DataSourcePanel/EditDataSource.js
A minor change: Added htmlFor attributes to label elements, according to Abi's suggestion.
> SWIK-469 Added htmlFor attributes

- components/Header/Header.js
* Autoclose of the sidebar
* No more log messages from the sidebar
* Small refinements
> SWIK-804 Revisioned the former PR and added some more logic

- components/Deck/ContentPanel/SlideModes/SlideEditPanel/SlideContentEditor.js
- components/Import/Import.js
See e.g.,
http://platform.experimental.slidewiki.org/deck/7-2/slide/105-16/105-16:3/edit
> SWIK 832 - change position and index of speaker note elements + SWIK

- components/Deck/Presentation/Presentation.js
> Fix for slides larger and smaller than 960*720

- actions/decktree/moveTreeNode.js
- actions/decktree/moveTreeNodeAndNavigate.js
- actions/decktree/moveTreeNodeWithRevisionCheck.js
- assets/css/custom.css
- components/Application.js
- components/Deck/TreePanel/Tree.js
- components/Deck/TreePanel/TreeNode.js
- components/Deck/TreePanel/TreeNodeList.js
- components/Deck/TreePanel/TreeNodeTarget.js
- components/Deck/TreePanel/TreePanel.js
- package.json
- services/decktree.js
- stores/DeckTreeStore.js
Reverts slidewiki/slidewiki-platform#238
> Revert "Revert "Swik 754 prototype drag and drop slide reordering""

- components/Deck/ContentModulesPanel/ContentDiscussionPanel/Comment.js
This is a very small bug fix.
The userid parameter was missing in Comment component. Because of this the author of comment replies was not shown in the activity feed.
> Added the missing userid parameter

- components/User/UserProfile/ChangePersonalData.js
- components/User/UserProfile/ChangePicture.js
- components/common/CountryDropdown.js
- components/common/LanguageDropdown.js
Added for/id to form fields in user settings page. Language/country dropdown still not correctly labelled & will need to be fixed with
Semantic-UI-React. Removed Uplad Image button from tab order.
> Improved accessibility on user settings page.

- components/Login/HeaderDropdown.js
- components/common/UserPicture.js
roles to user menu. Works ok with FireFox/NVDA but further improvements
needed for managing roles in Chrome.
> Adds empty alt tag & role=presentation to user image on header. Adds

- stores/DeckTreeStore.js
just corrected checking of count in tree after delete
> SWIK-887_last_slide_deletion_could_fail

- assets/ckeditor_config.js
> added space to redo build

- components/User/UserProfile/PrivatePublicUserProfile.js
- components/User/UserProfile/PublicUserData.js
- components/User/UserProfile/UserProfile.js
Added check in public profile if user is equals signed in user
> SWIK-879_404_public_profile

- components/Deck/ContentPanel/SlideModes/SlideEditPanel/SlideContentEditor.js
Do not show borders in container div elements of SVG drawings
> svg drawing container div with no border

- assets/css/PresentationDefaults.css
- components/Deck/ContentPanel/SlideModes/SlideEditPanel/SlideContentEditor.js
- components/Deck/ContentPanel/SlideModes/SlideViewPanel/SlideViewPanel.js
- components/Deck/Presentation/Presentation.js
Reverts slidewiki/slidewiki-platform#273
> Revert "SWIK-526, SWIK-716 and SWIK-806 Presentation alignment and consistency"

- .eslintrc
- actions/history/loadContentHistory.js
- actions/user/userSignOut.js
- components/AddDeck/AddDeck.js
- components/Deck/ContentModulesPanel/ContentQuestionsPanel/ContentQuestionAnswersItem.js
- components/Deck/ContentModulesPanel/ContentUsagePanel/ContentUsagePanel.js
- components/Deck/ContentModulesPanel/ContributorsPanel/util/ContributorsUtil.js
- components/Deck/ContentPanel/ContentActions/ContentActionsFooter.js
- components/Deck/ContentPanel/DeckModes/DeckEditPanel/DeckPropertiesEditor.js
- components/Deck/ContentPanel/SlideModes/SlideEditPanel/SlideContentEditor.js
- components/Deck/ContentPanel/SlideModes/SlideViewPanel/SlideViewPanel.js
- components/Deck/Presentation/Presentation.js
- components/Deck/Presentation/PresentationPrint.js
- components/Deck/Presentation/PresentationSlide.js
- components/Import/Import.js
- components/User/UserProfile/PrivatePublicUserProfile.js
- package.json
- test/unit/ContentModulesStore.js
Reverts slidewiki/slidewiki-platform#286
> Revert "Fix lint errors"

- components/Deck/ContentPanel/DeckModes/DeckEditPanel/DeckPropertiesEditor.js
- components/Search/SearchPanel.js
- components/common/LanguageDropdown.js
Just corrected the word. A portuguese could feel offended if not ;)
> Corrected typos with 'portuguese' word

- components/Deck/NavigationPanel/NavigationPanel.js
- components/DefaultHTMLLayout.js
- components/Header/Header.js
- components/Home/DeckList.js
- components/Home/Home.js
- components/Login/LoginModal.js
- server.js
- stores/ApplicationStore.js
- webpack/dev-server.js
- webpack/dev.config.js
Reverts slidewiki/slidewiki-platform#283
> Revert "Cookie eu"

- components/User/UserRegistration/UserRegistration.js
Updated id and names of form elements
> SWIK-1067_sign_up_fix

- actions/user/userprofile/fetchUser.js
I've implemented a quick fix that temporarily solves the problem (still old architecture/implementation). This may be merged in order to have a quick-fix of the problem. Please do not delete the branch.
I want to refactor (find a better solution) the whole functionality with Ali Khalili to get rid of the problem in the first case and to have it more resilient against issues.
> SWIK-1033-deadlock-user-service-unavailable

- components/Deck/TreePanel/TreeNode.js
Little accessibility fix on the tree panel.
> fixed accessibile name of treenodes by removing redundent aria-label

- components/Deck/ContentPanel/SlideModes/SlideEditPanel/SlideContentEditor.js
- custom_modules/simple-draggable/lib/index.js
> SWIK 1070   Input box controls displaying in presentation mode (not every slide)

- components/Deck/ContentPanel/SlideModes/SlideEditPanel/SlideContentEditor.js
- components/common/TemplateDropdown.js
Tested in Firefox, Firefox dev, Chrome, Safari
> SWIK 1102   Add slide templates from http  stable.slidewiki.org/deck/9319 3

- actions/user/userprofile/updateUsergroup.js
- components/User/UserProfile/UserGroupEdit.js
- components/User/UserProfile/UserGroups.js
- services/userProfile.js
Adopted new route params at /usergroup/createorupdate. Fixed that creator of a group is read wrong. Fixed datetime handling
> SWIK-1131_fix_group_management

- actions/user/registration/socialSignUp.js
- actions/user/userSignIn.js
- actions/user/userSignOut.js
- actions/user/userSocialSignIn.js
- actions/user/userprofile/fetchUser.js
- actions/user/userprofile/removeUser.js
- plugins/UserStorage/userStoragePlugin.js
Validate that everything still works and that the mentioned (Jira ticket) error has been solved.
> SWIK-1141 Added reload to sign in and sign out actions and removed it from the plugin

- components/User/UserRegistration/UserRegistration.js
Fixed an accessibility error (my error in missing it earlier)
@TBoonX @rmeissn could one of you check this has not affected the registration process?
> Fixed htmlFor tags in registration form

- actions/tags/updateTagsDeck.js
- components/AddDeck/AddDeck.js
- components/Deck/ContentPanel/DeckModes/DeckEditPanel/DeckPropertiesEditor.js
- components/Deck/ContentPanel/DeckModes/DeckViewPanel/DeckViewPanel.js
- services/deck.js
- services/presentation.js
Reverts slidewiki/slidewiki-platform#349
> Revert "SWIK 539   Deckedit component   edit (reveal.js) theme for deck"

- components/Deck/ContentPanel/SlideModes/SlideEditPanel/SlideContentEditor.js
- components/Deck/ContentPanel/SlideModes/SlideViewPanel/SlideViewPanel.js
Tested on http://localhost:3000/deck/1379-1/ in Firefox dev and chrome
with dev and build
> Add routine for switching to canvas-mode + checks + updated visuals + templates accordingly

- components/Application.js
- components/Deck/Deck.js
- components/Error/ServiceUnavailable.js
- stores/ServiceErrorStore.js
Please test at your end. I have tested by changing user microservice url. Without using this solution, it shows two error messages but after using this solution there is only one message.
> Swik 1223 removing duplicate service error msg from site

- actions/saveDeckEdit.js
- actions/slide/loadSlideView.js
- actions/slide/saveSlide.js
- actions/tags/cancelEditTag.js
- actions/tags/changeEditMode.js
- actions/tags/loadDataTagCount.js
- actions/tags/loadTags.js
- actions/tags/newTag.js
- actions/tags/removeTag.js
- actions/tags/saveTags.js
- actions/tags/showMoreTags.js
- actions/tags/updateTagsDeck.js
- actions/tags/updateTagsSlide.js
- common.js
- components/Deck/ContentModulesPanel/TagsPanel/TagList.js
- components/Deck/ContentModulesPanel/TagsPanel/TagsPanel.js
- services/deck.js
- services/slide.js
- stores/TagsStore.js
I adopted the tag data structure.
I updated all corresponding actions.
I improved the UI a bit with loading indicator, notifications, an extra save button and improved styling.
Also a few exception sources are removed out of the code like undefined objects
> Swik 1112   tags currently not saved in tag tab on experimental

- components/AddDeck/AddDeck.js
- components/Deck/ContentPanel/DeckModes/DeckEditPanel/DeckPropertiesEditor.js
- components/common/LanguageDropdown.js
I just enhanced the general LanguageDropdown component, used it in Edit Deck component, reordered one field and used full names for licences in Edit Deck.
> Swik 1234 inconsistent views related deck

- server.js
Putting back the missing line of code which registers like service.
> Put back missing registration of like service

- components/Deck/Deck.js
- components/Deck/InfoPanel/InfoPanel.js
- components/Deck/TreePanel/TreePanel.js
- components/Header/Header.js
- stores/DeckPageStore.js
Work by Abi on width of deck page + extra vertical menu - see https://slidewiki.atlassian.net/browse/SWIK-788
> SWIK 788 Full Width deck page

- components/Deck/ContentPanel/AttachSubdeck/AttachDeckList.js
Now, when an user selects one deck from the list, is is marked with the aria-label   aria-selected=true. For items not selected,aria-selected=false
Branch SWIK-1308-markDeckItems
Available at. http://svalero.dsic.upv.es:3000/
> Swik 1308 mark deck items

- components/User/UserProfile/PopularDecks.js
- components/User/UserProfile/PrivatePublicUserProfile.js
Changed default sort in my decks
> SWIK-786_myDecks_order

- configs/general.js
- services/user.js
Outcommented API key in configs/general.js. Adopted changes of resetPassword route.
> SWIQ-1100_hashing_password_on_server

- actions/decktree/forkDeck.js
- actions/decktree/saveTreeNode.js
- components/Deck/ActivityFeedPanel/ActivityItem.js
- components/Deck/ContentPanel/ContentActions/ContentActionsFooter.js
- components/User/UserNotificationsPanel/UserNotificationsItem.js
- services/discussion.js
- stores/UserNotificationsStore.js
Download (epub and pdf) and fork activities are recorded using the activity-service (and shown in the activity feed panel).
Fork activity_type is added, since it wasn't a part of the initial implementation.
Adding of 'edit' activity when renaming a node was implemented.
Also some modifications were made to handle unknown user_id values.
> Swik 1326 download and fork activities

- components/Login/LoginModal.js
- components/User/UserRegistration/UserRegistration.js
commented out facebook buttons
> SWIK-1213_remove_facebook

- services/usage.js
This solves a bug where the usage tab did not show on some occasions titles and usernames.
> Fix usage tab not showing users and titles

- components/Deck/Deck.js
- components/Deck/InfoPanel/InfoPanel.js
First simple prototype of Info Panel
> Added basic info panel design

- components/Deck/Deck.js
> add horizontal padding to first and last column of deckview

- actions/user/userprofile/fetchUser.js
- services/userProfile.js
I just added wrong data handling in the action fetchUser which fixes the unwanted page reload and 404 Error
> SWIK-1304_userservice_404_breaks_flux

- components/User/UserNotificationsPanel/UserNotificationsItem.js
- components/User/UserNotificationsPanel/UserNotificationsList.js
- components/User/UserNotificationsPanel/UserNotificationsPanel.js
- stores/UserNotificationsStore.js
Fixing a bug which is preventing unread notifications to be marked (and count to be displayed).
Fixing accessibility issues.
> BugFix - Swik 644 display notifications for users decks slides

- components/Deck/ActivityFeedPanel/ActivityItem.js
- components/User/UserNotificationsPanel/UserNotificationsItem.js
- components/User/UserNotificationsPanel/UserNotificationsPanel.js
- stores/UserNotificationsStore.js
Small modification to improve (fix) marking notifications as read
Also modified display of semantic ui 'reply' icon which for some reason is smaller then other.
> Swik 644 display notifications for users decks slides

- components/User/UserProfile/ChangePersonalData.js
save user profile now reads language from cookie
Have to be merged with same branch of user-service
> SWIK-1346_userprofile_could_not_be_saved

- components/AddDeck/AddDeck.js
- stores/AddDeckStore.js
Removed license dropdown from Add Deck page
> SWIK-1409 Remove license dropdown

- components/Home/DeckList.js
a PR in deck-service needs to be merged before this
> replace revision count with fork count in recent decks listing

- common.js
- components/Login/LoginModal.js
- components/Login/ResetPassword.js
- components/User/UserProfile/ChangePersonalData.js
- components/User/UserProfile/Integrations.js
- components/User/UserRegistration/UserRegistration.js
- components/User/UserRegistration/UserRegistrationSocial.js
Added reading language from cookie to common.js and used it in the components which send the language to the userservice
> SWIK-1411_language_is_read_wrong_in_userprofile_and_registration

- services/userProfile.js
made sure that the member property is an array before calling reduce.
> SWIK-1435_group_without_members_could_not_be_saved

- actions/user/userprofile/updateUsergroup.js
- components/User/UserProfile/UserGroupEdit.js
Improved filtering out the deleted user from members. Added cloger usage to an action.
> SWIK-1422_delete_correct_user_from_group

- components/Deck/ContentModulesPanel/ContentQuestionsPanel/ContentQuestionAnswersList.js
Added Edit button for each question. Show only when a user is logged in and is also the deck creator.
> Swik 1434 show edit button when logged in

- components/Deck/ActivityFeedPanel/ActivityItem.js
- components/Deck/ContentModulesPanel/DataSourcePanel/DataSourceItem.js
- components/User/UserNotificationsPanel/UserNotificationsItem.js
- webpack/dev-server.js
Activity feed panel (Data sources and Notifications panels, also) doesn't properly display special letters (like Spanish Accents) in slide titles. This has been solved in this branch, using cheerio.
> Swik 1428 fix activity feed for slides with special letters in titles

- components/LocaleSwitcher/LocaleSwitcher.js
- components/User/UserProfile/CategoryBox.js
- components/User/UserProfile/ChangePersonalData.js
- components/User/UserProfile/UserProfile.js
* Moved language chooser to user-settings (right column)
* Rename to "User Interface Language"
* Deactivate auto update feature
* Refactored LocaleSwitcher component
> SWIK-1452 move language chooser

- actions/decktree/loadDeckTree.js
- actions/permissions/loadPermissions.js
- components/Deck/ActivityFeedPanel/ActivityFeedPanel.js
This PR addresses issues [SWIK-1465](https://slidewiki.atlassian.net/browse/SWIK-1465) and [SWIK-1453](https://slidewiki.atlassian.net/browse/SWIK-1453).
> Swik 1453 501 after deck creation

- actions/loadLegacy.js
- configs/routes.js
- server/handleServerRendering.js
fix, the architecture is slightly changed
> Swik 1521 bug

- components/Deck/ContentModulesPanel/ContributorsPanel/ContributorItem.js
Added width attribute to call of UserPicture
> SWIK-1545_contributors_list_throwing_NaN_error

- client.js
> removed hashtag after redirect

- components/Deck/ContentPanel/AttachSubdeck/AttachDeckList.js
- components/Deck/ContentPanel/AttachSubdeck/AttachSlides.js
- components/Deck/ContentPanel/AttachSubdeck/AttachSlidesModal.js
- components/Deck/ContentPanel/AttachSubdeck/AttachSubdeckModal.js
> SWIK-1553 wrong deck list navigation

- components/User/UserRegistration/UserRegistration.js
changed link to Terms to /imprint
> SWIK-1555_link_to_imprint

- components/Report/ReportModal.js
> SWIK-1556_exchange_Klaas_email

- actions/loadDeck.js
- services/deck.js
this fixes a bug with loading forks for non logged-in users
> Fix bug when loading forks for non logged in users

- components/Deck/ContentModulesPanel/ContentHistoryPanel/ContentChangeItem.js
- components/Deck/ContentPanel/ContentActions/DownloadButton.js
Removed a warning, very minor change
> Swik 1589 download button

- actions/error/spamDetectedError.js
- actions/user/userprofile/fetchUser.js
- components/Error/util/ErrorDescriptionUtil.js
- stores/ErrorStore.js
Added error: SPAM detected. 
New error is used when a public user profile of a suspended user was actuated
> SWIK-1625 403_handling_of_userprofile

- actions/user/userSignIn.js
- components/Login/LoginModal.js
> [SWIK-1624_message_for_suspended_login] Added handling of 403 response

- components/Deck/Diffview/Diffview.js
- components/Deck/Diffview/diff_funcs.js
Temporary adding client logs since the **local master branch** and **experimental** diffs (using the same slide and revisions) show different results.
> diff-view minor fixes and logs

- components/Login/HeaderDropdown.js
The className of the menu associated to the dropdown button has been updated to the requirements of the semantic-ui version we use.
> Swik 1767 : fix how  dropdown user menu is displayed

- package.json
updated the package json to add the latest verion of semantic-ui-react:0.74.2
In previous version input lists are not well rendered, dropbox lists options are not read aloud, and more problems. 
Now, the input list shows the possibilities to the user in the ContactForm. You can check it in http://svalero.dsic.upv.es:3000/contactus
In the original branch in which the contactForm was implemented, also this entry was updated. At a later point, this change was reverted.
> SWIK-1763-fixContactForm 

- actions/decktree/moveTreeNode.js
- components/Deck/ActivityFeedPanel/ActivityItem.js
- components/User/UserNotificationsPanel/UserNotificationsItem.js
- stores/UserNotificationsStore.js
When a slide or a subdeck node is moved, a 'move' activity is created and shown in the activity feed.
> SWIK-1790 adding move activity

- components/PresentorHTMLLayout.js
- server/handleServerRendering.js
using a different layout for presentation mode
> SWIK-1839 remove feedback button presentations mode

- components/Home/Terms.js
> Swik 1855 edit terms

- components/PresentationRoomsHTMLLayout.js
- components/webrtc/presentationBroadcast.js
Added a missing library - dropdown list of peers in "Ask a question" works now.
Maybe wait for more bugs to arise.
> Fix bugs of presentations rooms

- components/Deck/ContentPanel/ContentActions/ContentActionsHeader.js
Reverts slidewiki/slidewiki-platform#639
> Revert "SWIK 1863 move slide controls"

- components/common/UploadMediaModal.js
> SWIK-1899 accessibility improvements for media upload modal

- components/Deck/ContentPanel/ContentActions/ContentActionsFooter.js
- components/Deck/ContentPanel/ContentActions/DownloadModal.js
- components/Home/Features.js
- components/Home/Home.js
- components/Home/Welcome.js
Change "Presentation mode" to "Slideshow mode" in UI to be more accurate and distinguish it from the Presentation rooms
> Swik 1909 slideshow tooltip

- components/User/UserProfile/UserProfile.js
Wasn't able to test the changes quickly, as experimental seems to be down. Waiting for it to come online again in order to test that everything still works.
Please don't merge until someone verified these changes!
> SWIK-1925 Internationalisation

- components/Login/ResetPassword.js
- components/User/UserProfile/Integrations.js
- components/User/UserRegistration/UserRegistrationSocial.js
Please test and review these changes - social providers are not testable on localhost.
> SWIK-1920 Internationalisation

- components/User/UserRegistration/UserRegistration.js
UserRegistration page now uses intl.
This page access to this.props.UserRegistrationStore.errorMessage. this message should be translated in the origin, because it is not possible to add a variable as a defaultMessage.
> SWIK-1918-translate 

- components/Deck/InfoPanel/PresentationsPanel.js
- services/presentation.js
test with coexisting PR of signaling-service
Requested by users at the plenary in Leipzig
> Added Opening Time to presentation rooms

- components/Home/About.js
updated text on About Us page.
> Swik 2041 update about us

- components/Import/ImportModal.js
Recent ImportModal needs an extra state to control it is showing an error to the user.
This fix adds it in order to prevent possible problems. Also, it changes the way we indicate which colors we want to use for buttons, in order to avoid some warnings.
> Swik 2058 bug fix

- components/User/UserProfile/DeckCard.js
Improved formatting of metadata, removed reducendent tabindex, added aria-label to deck title
> Swik 2076 accessibility deck card

- assets/ckeditor_config.js
config.fillEmptyBlocks = true; instead of false, to reset it to default
addition of &nbsp; in empty/newline blocks by CKeditor
> Put space HTML character in empty blocks to have view and edit the same

- actions/user/userprofile/fetchUser.js
Fixes issue that appears when opening other user's playlist tab.
@kadevgraaf this should go into the release too
> Fix 404 error when opening other user's playlists tab

- components/Deck/ContentPanel/DeckModes/DeckViewPanel/DeckViewPanel.js
Improved the layout of the deck meta data. Remove theme from the meta data.
> Swik 2152 improve meta layout

- components/Deck/ContentPanel/SlideModes/SlideControl.js
Removed shortkeys from tooltips and simplified languages
> Change tooltip and aria-labels on slide controls

- components/DeckCollection/Modals/NewCollectionModal.js
- components/DeckCollection/Modals/UpdateCollectionModal.js
Fixes issue about not being able to assign a user group that I belong to a playlist.
> Fix addition of user group I belong to a playlist

- components/Deck/ContentPanel/DeckModes/DeckEditPanel/DeckEditPanel.js
- components/User/UserProfile/PrivatePublicUserProfile/UserDecks.js
- components/User/UserProfile/PrivatePublicUserProfile/UserMenu.js
- package.json
- services/userProfile.js
- stores/UserProfileStore.js
Reverts slidewiki/slidewiki-platform#848
> Revert "SWIK 2147   Add templates to slide content instead of overwriting it"

- components/BasicHTMLLayout.js
- components/DefaultHTMLLayout.js
- components/Footer/Footer.js
- components/Home/Imprint.js
- components/PresentationRoomsHTMLLayout.js
- components/PresentorHTMLLayout.js
- plugins/googleAnalytics/ga.js
- changed Imprint page
- changed link 'Data Protection' to point to TIB data protection site
- changed Copyright in footer to 2018
- disabled Google Analytics
> Gdpr adoption

- services/searchresults.js
- stores/DeckFamilyStore.js
This is a fix for undefined number of likes in the DeckFamily panel.
> SWIK-2259 Getting number of likes for deck family

- components/User/UserRegistration/UserRegistrationSocial.js
- stores/UserRegistrationStore.js
Added swal alert when social error occur
> SWIK-2017_social_sign_up_error_responses

- components/Login/LoginModal.js
- stores/UserProfileStore.js
Made isLoading variable be part of the compontents state and removed forceUpdate() calls.
> SWIK-2281_LoginModal_stack_exceeded

- actions/user/registration/newSocialData.js
- actions/user/userSocialSignIn.js
- components/Login/LoginModal.js
- stores/UserRegistrationStore.js
Fix number 2.
In order to test the social login error behaviour use the following code:
```
this.handleDummyClick = this.handleDummyClick.bind(this);
handleDummyClick(e) {
e.preventDefault();
this.provider = 'github';
$('.ui.login.modal').modal('hide');
localStorage.setItem(MODI, 'login');
localStorage.setItem(NAME, '');
let thatContext = this.context;
async.series([
function(callback) {
thatContext.executeAction(newSocialData, {});
callback(null, 1);
},
function(callback) {
thatContext.executeAction(userSocialSignIn, {});
callback(null, 2);
}
]);
}
<br/><br/>
<a href="#" onClick={this.handleDummyClick}>
dummy
</a>
```
> Swik 2281 login stack exceed try2

- components/common/UploadMediaModal.js
- now the Licence Modal uses Intl
- accesibility problems of the modal patched
- Url to terms and conditions added
> Swik 2048 fix license modal

- actions/loadDeck.js
- components/Deck/ContentPanel/AttachSubdeck/AttachDeckList.js
- components/Deck/ContentPanel/DeckModes/DeckViewPanel/DeckViewPanel.js
- components/Deck/ContentPanel/Translation/DeckTranslationsModal.js
- components/Deck/InfoPanel/InfoPanelInfoView.js
- components/Deck/InfoPanel/TranslationItem.js
- components/Deck/TreePanel/TreePanel.js
- intl/default.json
- stores/TranslationStore.js
First improvements on translations - atm just bugfixes no UI changes.
> Swik 2363 improvements translations ui

- components/Search/AutocompleteComponents/UsersInput.js
- services/suggester.js
Updates the user filter dropdown in the search forms. 
Also works with display names as it is merged in user-service.
> Update user search dropdown in search form

- components/Application.js
Edited message due to issues with the length of message on small screens.
> shortened cookie message

- components/Footer/Footer.js
Seems to be fine without the style in desktop, tablet and mobile view.
> SWIK-2030 remove some style

- configs/routes.js
Bug discovered by @kprist in SWIK-862
> SWIK-2485 Fix that presentation mode won't start on a specific slide

- components/Deck/ContentModulesPanel/ContentDiscussionPanel/Comment.js
- services/discussion.js
This PR enables displaying of comments for all (current and past) deck/slide revisions.
Service side (discussion-service) modifications have already been merged.
> Swik 2441 show comments for all revisions

- actions/contentdiscussion/addComment.js
- actions/contentdiscussion/addReply.js
- actions/decktree/addTreeNode.js
- actions/decktree/addTreeNodeList.js
- actions/decktree/deleteTreeNode.js
- actions/decktree/moveTreeNode.js
- actions/decktree/saveTreeNode.js
- actions/loadDeck.js
- actions/saveDeckEdit.js
- actions/slide/saveSlide.js
- components/Deck/ContentModulesPanel/ContentDiscussionPanel/AddReply.js
- components/Deck/ContentModulesPanel/ContentDiscussionPanel/Comment.js
- components/Deck/ContentPanel/AttachSubdeck/AttachSlidesModal.js
- components/Social/SocialShare.js
Activities are enriched with parent_content_id and top_parent_content_id parameters (where applicable).
Service side code modifications are already merged.
> SWIK-2490 Include parent deck id activities

- components/DefaultHTMLLayout.js
- components/PresentationRoomsHTMLLayout.js
Will add new feedback link to Footer in SWIK-2466 branch along with other Footer edits.
> Removed JIRA feedback button

- actions/decktree/moveTreeNodeAndNavigate.js
Fixed the redirect after sorting slides
> Swik 2536 Fix wrong redirect in move tree

- components/AddDeck/AddDeck.js
Added semantic ui classes to checkbox for publishing imported deck
> Swik 2546 fix hidden publish checkbox 

- components/Deck/TreePanel/TreePanel.js
- stores/ContentStore.js
- Fix for problem with playing subdecks for the "play presentation" button on top of the deck tree
- Fix playing nested subdecks for play button in content footer
> Swik 2549 fix play buttons for sub decks

- actions/search/loadSearchResults.js
- components/Search/SearchPanel.js
- components/Search/SearchResultsPanel/Facets.js
- services/searchresults.js
Current state: 
* Adds education levels in facets/filters
* Both translations and forks are displayed together in the "other versions available" section in the search results.
* Topics are displayed as Tags in the search filters
The following PRs should be merged first: 
https://github.com/slidewiki/solrserver-config/pull/17
https://github.com/slidewiki/search-service/pull/28
https://github.com/slidewiki/deck-service/pull/148
> Swik 2509 translations

- services/deck.js
This is needed to index subjects (modelled as tags) in deck service and search service.
> Send tag type when updating/saving any tags to deck service

- actions/history/revertRevision.js
- components/AddDeck/AddDeck.js
- components/Deck/ContentModulesPanel/ContentHistoryPanel/DeckRevision.js
Fix redirects to deck view: after creating a new deck and for the history tab.
> Swik 2541 change redirect new deck

- components/UserGroups/Details.js
- components/UserGroups/UserGroupPage.js
Added buttons to add/remove admin role of users. Fixed reading of admin role of user.
> SWIK-2545_admin_roles_in_UI

- components/Footer/Footer.js
- components/Header/Header.js
Added header and footer tags for the site header and footer
> Swik 2577 add header and footer tags

- assets/ckeditor_config.js
Added skin to CKEditor config file, to prevent error during loading CKEditor
> Swik 2583 fix skin error CKEditor

- components/Deck/ActivityFeedPanel/ActivityFeedPanel.js
- components/Deck/ContentModulesPanel/ContentModulesPanel.js
- components/Deck/ContentModulesPanel/ContributorsPanel/ContributorItem.js
- components/Deck/ContentModulesPanel/ContributorsPanel/ContributorsPanel.js
- components/Deck/ContentPanel/ContentActions/ContentActionsHeader.js
- components/Deck/ContentPanel/DeckModes/DeckViewPanel/DeckViewPanel.js
- components/Deck/Deck.js
- components/Deck/InfoPanel/InfoPanelInfoView.js
- components/Deck/InfoPanel/PresentationsPanel.js
- components/Footer/Footer.js
- components/Login/LoginModal.js
- components/common/UserPicture.js
For SWIK 2514 - improves heading hierarchy and regions
SWIK-2595 - consistent colour of Unlisted label and remove from focus order
SWIK-2561 - edit message on ContentActionHeader re small screens instead of mobile
> Improves headings, regions, UI consistency etc

- components/Deck/ContentModulesPanel/ContentQuestionsPanel/ContentQuestionsPanel.js
- components/Deck/ContentModulesPanel/ContentQuestionsPanel/ExamList.js
As requested, the Exam mode is opened in a new tab.
> SWIK-2585 Open exam mode in a new tab

- actions/loadDeckView.js
- actions/slide/loadSlideView.js
- components/DefaultHTMLLayout.js
- stores/ApplicationStore.js
Reverts slidewiki/slidewiki-platform#1129
I get a fatal error on navigating to a random deck: 
TypeError: Cannot read property 'replace' of undefined
at ApplicationStore.getPageDescription (/Users/kadevgr/slidewiki-platform/stores/ApplicationStore.js:44:37)
> Revert "Add Open Graph meta data"

- components/Deck/ContentPanel/SlideModes/SlideEditPanel/SlideContentEditor.js
> Fix alt-text quotes for images in slide editor 

- actions/loadDeckView.js
> Added page more descriptive page titles for landing and overview page

- components/Home/Home.js
- components/Home/StaticPage.js
> Add button role and tab index to signin text on homepage

- components/Deck/ContentPanel/ContentActions/ContentActionsHeader.js
- services/slide.js
This fixes a bug where slides in markdown were not saved. 
Fixes #1156
> Removed unneeded code to fix Markdown editor saving

- assets/css/custom.css
- components/AddDeck/AddDeck.js
- components/Deck/ContentModulesPanel/TagsPanel/TagInput.js
- components/common/SWAutoComplete.js
Fixes #1169, and fixes #1167 
In addition to the reported accessibility issues, some extra accessibility improvements are made. The aria-required, aria-invalid and aria-labelledby attributes are used on the addDeck page.
> Fix accessibility issues iOCW

- stores/TranslationStore.js
> fix: issue with loading slides with an undefined language

- components/Deck/ContentPanel/SlideModes/SlideViewPanel/SlideContentView.js
> fix: overflow of content when using old (non-canvas) slides

- .github/workflows/main.yml
- actions/deckQuality/loadDeckQuality.js
- components/Deck/ContentModulesPanel/ContentModulesPanel.js
- components/Deck/ContentModulesPanel/ContentQuestionsPanel/ContentQuestionEdit.js
- components/Deck/ContentModulesPanel/QualityPanel/CheckDescriptiveNames.js
- components/Deck/ContentModulesPanel/QualityPanel/CheckHierarchicalDesign.js
- components/Deck/ContentModulesPanel/QualityPanel/CheckMetadataAdherenceQuality.js
- components/Deck/ContentModulesPanel/QualityPanel/CheckMetadataQuality.js
- components/Deck/ContentModulesPanel/QualityPanel/CheckMultipleLanguages.js
- components/Deck/ContentModulesPanel/QualityPanel/CheckQuestionDistractors.js
- components/Deck/ContentModulesPanel/QualityPanel/CheckQuestions.js
- components/Deck/ContentModulesPanel/QualityPanel/QualityPanel.js
Adds a quality check for decks in the ContentModules panel.
Todo: 
Screenshots:
@rezatavakoli you can use this branch and extend it with checks you are going to implement
> feat(QualityContentModule): display a quality check for decks 

- assets/ckeditor_config.js
- assets/ckeditor_config_basic.js
Add h1 and h2 headline to ckeditor. Fixes #1219
> Add h1 and h2 to ckeditor

- components/Home/Accessibility.js
- components/Home/Home.js
- components/Home/StaticPage.js
- components/Search/SearchResultsPanel/SearchResultsPanel.js
Add missing structural elements such as <p>. Fixes #1222
> fixes #1222 : missing structural element

- components/Deck/DeckLanguageMenu.js
> Fix changing language with keyboard navigation 

- assets/css/home-layout.css
- components/Home/ContactUs.js
- components/Login/LoginModal.js
- components/Login/ResetPassword.js
- components/Report/ReportModal.js
- components/Search/SearchResultsPanel/SearchResultsPanel.js
- components/User/UserProfile/RecommendedDecks.js
- components/User/UserRegistration/UserRegistration.js
> Fix content sizing small screens

- assets/css/home-custom.css
- components/User/UserProfile/ChangePersonalData.js
- components/common/CountryDropdown.js
> Fix zooming text 200%

- assets/css/custom.css
- components/Deck/ContentModulesPanel/TagsPanel/TagInput.js
- components/Deck/ContentPanel/AttachQuestions/AttachQuestionsModal.js
- components/Deck/SlideEditLeftPanel/SlideEditLeftPanel.js
- components/Search/SearchPanel.js
- components/common/SingleItemAccordion.js
> Fix focus color

- components/Deck/ContentPanel/SlideModes/SlideEditPanel/MarkdownEditor.js
- components/Search/AutocompleteComponents/KeywordsInputWithFilter.js
- components/Search/SearchPanel.js
Fix issues regarding info and relationships in the search text and markdown editor. #1224
> Fix relationships issues regarding the search text and markdown text #1224

- Dockerfile
> chore: upgrade node version Dockerfile
