- components/Deck/ContentPanel/SlideModes/SlideEditPanel/SlideContentEditor.js
- components/DefaultHTMLLayout.js
Also addresses SWIK-489 - Create border around divs in edit mode for
clearly showing draggable elements
> SWIK-537 Reposition (drag) absolute elements from PPTX2HTML import

- components/Header/Header.js
In components/Header.js, at line 28, tehre is a typo in the className assigned to UserNotificationsBadge. The line is:
` <UserNotificationsBadge className="zi item"/>`
It should be:
` <UserNotificationsBadge className="ui item"/>`
> SWIK534 ClassName of UserNotificationsBadge change to ui item

- components/Deck/ActivityFeedPanel/ActivityItem.js
- components/Deck/ActivityFeedPanel/ActivityList.js
- services/activities.js
Activity feed now shows activities for the selected slide/deck.
If a deck is selected, activities for its subdecks and slides are also shown.
Most of the code changes to enable this were done on the activity-service.
This branch also solves problems with slide/deck links (SWIK-596).
> Swik 573 show activities for selected slide/deck

- components/Deck/ActivityFeedPanel/ActivityList.js
- components/Deck/ContentPanel/SlideModes/SlideEditPanel/SlideContentEditor.js
- components/Deck/ContentPanel/SlideModes/SlideViewPanel/SlideViewPanel.js
- custom_modules/simple-draggable/lib/index.js
- package.json
- stores/SlideEditStore.js
Only in slide-content editor (ugly hacks for now (testing/QA) cover
your eyes / burn it with fire)
- calculate scale ratio based on edit react component and size of pptx
slide content
- use scale ratio to re-initiate mouse-calculation of resize & drag in
simple-draggable. used clone-node to remove event listeners.
Tested in firefox and chrome with deck 344 -
http://localhost:3000/deck/344-2/slide/1394-1/1394-1:8/edit
I assume(!) this works also in newer decks/imports
> SWIK 550  Make slide content fit in slide view and edit component

- components/User/UserRegistration/UserRegistration.js
User Registration component gets the user language from the browser. There are cases when browser gives two-character code (e.g. 'de') instead of five-character, which is needed for the user-service.
This is a temporary fix for this problem.
> Swik 611 fix signup language atribute

- components/Deck/ContentPanel/SlideModes/SlideEditPanel/SlideContentEditor.js
Part of 
SWIK-623
When user presses any action to add or deck/slides and they are not signed in they should be warned and prompted to sign-in
For save slide
> SWIK 465  Replace  edit  button in deck edit with  save  when editing + use icon from semantic UI

- components/Application.js
Previously, I had named Error component as `ErrorComponent` but it was later changed to `Error`. This change missed in Application.js which was still using `import ErrorComponent ...`.
> Fix for SWIK-651. ErrorComponent changed to Error

- components/Deck/Presentation/Presentation.js
Very minor change.  Should make the display consistent between the Presentation mode and View and Edit modes.
See also the change in the SWIK-684 branch in the slidewiki/reveal.js library.  That will adjust the default size of the `white.css` file to 28px making the `<h1>` element 70px (2.5em)
> SWIK-684 Make CSS consistent for presentation mode and display slightly better

- components/Deck/ContentModulesPanel/ContentDiscussionPanel/ContentDiscussionPanel.js
This is a small fix that displays an error when comment title or text are empty.
In the future, we will consider allowing comment title to be empty.
> SWIK-642 Added notifications for empty comment fields

- actions/decktree/saveTreeNode.js
- components/Deck/ContentPanel/SlideModes/SlideEditPanel/SlideContentEditor.js
This PL fixes the problem of a slide's title reverting to the title of the first slide visited after editing and saving it, as described by @abijames in [SWIK-656](https://slidewiki.atlassian.net/browse/SWIK-656).
> Fix slide title reverting to that of first slide after edit

- components/AddDeck/AddDeck.js
- services/import.js
Selected (or default) language on the 'Add Deck' form is now sent to the import micro-service, so that the it can pass the language parameter when creating a new deck.
Also, the selected license is now used, instead of the hard-coded, default one.
> Swik 714 pptx import default language

- services/user.js
Error description: When trying to reset a users password a message appears saying that the users mail address was not found in the database, even though the user account is existing.
This was caused because in services/user.js the call against the userservice's /passwordReset was implemented as a POST.
Fix: changing post to put.
> SWIK-731 now using PUT instead of POST against /resetPassword

- components/Login/LoginModal.js
- components/User/UserProfile/ChangePassword.js
- components/User/UserProfile/UserSettings.js
- components/User/UserRegistration/UserRegistration.js
- configs/general.js
- services/user.js
- services/userProfile.js
I've exchanged the in-service password hashing with one that is in most cases executed client-side. This is a huge security improvement, but doesn't tackle the isomorphic approach of fluxible. Thus, a plain text password might be sent to the server-side rendering in case someone uses the isomorphic characteristic.
How to test: Can you still login with your (existing) credentials? Can you register a new user and login? Can you alter your password and still login?
> SWIK-453 Converted to client-side password hashing

- components/Deck/ContentPanel/DeckModes/DeckViewPanel/DeckViewPanel.js
Simplified the earlier code that extracted language name from language code. It will work when the support for more languages, apart from English, will be added to the platform.
> Swik 702 simplify language extraction on deckview

- actions/datasource/cancelEditDataSource.js
- actions/datasource/newDataSource.js
- actions/datasource/showMoreDataSources.js
- components/Deck/ContentModulesPanel/ContentDiscussionPanel/AddComment.js
- components/Deck/ContentModulesPanel/ContentDiscussionPanel/ContentDiscussionPanel.js
- components/Deck/ContentModulesPanel/DataSourcePanel/DataSourcePanel.js
- components/Deck/ContentModulesPanel/DataSourcePanel/EditDataSource.js
- components/Deck/ContentModulesPanel/DataSourcePanel/Scrollbars/ShadowScrollbars.js
- components/Deck/ContentPanel/SlideModes/SlideEditPanel/SlideContentEditor.js
- services/datasource.js
- services/slide.js
- stores/DataSourceStore.js
-Changed some button icons and labels.
-Added 'show more' link to display all data sources (initially, only first 10 data sources are displayed).
-When saving the slide after editing, data sources are taken from the DataSourceStore and added to the payload of the saveSlide call. Thus, new slide revision gets data sources copied from the previous revision. Latest changes in PR [#44](https://github.com/slidewiki/deck-service/pull/44) are needed in the deck-service.
> Swik 469 adding sources of slides

- components/Deck/ContentPanel/SlideModes/SlideEditPanel/SlideContentEditor.js
- custom_modules/simple-draggable/lib/index.js
Related to import of SVG graphics.
Surrounding div with no width and height, outside PPTX canvas, is
created, which causes problems with editing.
Now fixed by detection and by also applying drag and resize function to
children of absolute elements in slide edit content
See e.g.
http://platform.experimental.slidewiki.org/deck/3-1/slide/61-1/61-1:26/e
dit
> SWIK-813 remove empty absolute elements in slide content

- actions/decktree/saveTreeNode.js
- stores/DeckTreeStore.js
This PR fixes an issue with the deck tree not being updated with the new rev number after a slide rename.
It created a problem with reordering after a rename, as the old revision with the old title was ultimately moved.
> Fix deck tree not updating slide rev number on rename

- components/Deck/ContentPanel/DeckModes/DeckEditPanel/DeckPropertiesEditor.js
Makes these buttons activate on Enter/Spacebar when they have focus. However, when testing on my localhost, I was now not directed to the View tab after they are activated. Please can someone test further and see if they can replicate this? The keyboard activation is more important than the redirect to the view tab at the moment.
> Changed Save / Save As / Cancel buttons to <button> 

- components/Import/Import.js
Now the files are filtered also by their extension, so only presentation formats are showed when trying to upload a file in the add deck view.
> Restricting file formats in the input tag.

- actions/slide/loadSlideEdit.js
- app.js
- components/Deck/ContentPanel/ContentActions/ContentActionsFooter.js
- components/Deck/ContentPanel/SlideModes/SlideEditPanel/SlideEditPanel.js
- stores/ContentActionsFooterStore.js
When users select the edit tab to edit an slide, it expands the layout and the decktree is hidden. When users exit from editing an slide, clicking in other option, the original layout is restored. Users can restore the layout while they are editing clicking the restore button (at the footer actions bar). 
Changes at code:
* Components modifications:
* SlideEditPanel.js: 
- Unused imports removed
- ComponenWillUmount() added: executes restoreDeckPageLayout action
* ContentActionFooter.js: it has a button to expand and collapse the page layout. In order to make it consistent with this auto-hidden process, this component has been connected to an store. The store returns the status layout: expanded or not. Depending of this status, the button displayed allows expand or restore the page …
> SWIK-787 auto hide decktree

- components/Deck/NavigationPanel/Breadcrumb.js
- components/Deck/TreePanel/TreeNode.js
The DB stores the data in the following manner:
`&#xBF;` for `¿`
Simple data type casting on the client did the trick.
> A test deck could be found in the comment section of the respective ticket
> SWIK-633 Fix render issue of language specific characters

- actions/decktree/forkDeck.js
- components/Deck/TreePanel/TreePanel.js
- services/deck.js
This PR makes the necessary changes in order for the fork button to work with the updated deck-service fork.
> Update fork button for new forking

- README.md
- components/Deck/ContentPanel/DeckModes/DeckViewPanel/DeckViewPanel.js
- components/User/UserProfile/DeckCard.js
- configs/microservices.sample.js
- docker-compose.yml
- microservices.js.template
I've removed the image-service from the docker-compose and microservices.config file, as the service will be discarded (stopped & removed). I've changed the thumbnail retrievel code to match the new API of the file-service.
I haven't tested the changes yet, as I wait for approval of slidewiki/file-service#2 and https://github.com/slidewiki/deck-service/pull/63 first. I'll comment this PR again as soon as the other PR has been merged.
> SWIK-1061 Exchanged the thumbnail retrievel code to use the new file-service API

- custom_modules/simple-draggable/lib/index.js
Earlier fix sets $('body').css('overflow', 'hidden');
But this removes scrollbar, shifting content to right, and this may
make a user miss the button once clicked.
> Revert change to prevent scrolling when draggin

- actions/activityfeed/loadActivities.js
- actions/loadContentModules.js
- components/Deck/ContentModulesPanel/ContentModulesPanel.js
- configs/routes.js
Just a couple of small changes to fix the SWIK-1113 bug:
Code for changing page title to 'Activities' is removed from loadActivities and loadContentModules actions, which are called from the loadDeck action, and added to the action for 'activities' page in routes.js.
> Swik 1113 fixing page title activities

- actions/loadRecent.js
Added handling of 404 when loading recent decks
> SWIK-1096_error_when_there_are_no_recent_decks

- services/user.js
Identifier is now always send as string
Just two calls of toString() of a parameter when send to the user-service.
> SWIK-1213_social_login_facebook_bug

- actions/loadDeck.js
- actions/permissions/hideNoPermissionsModal.js
- actions/permissions/showNoPermissionsModal.js
- components/Deck/ContentModulesPanel/ContentHistoryPanel/ContentHistoryItem.js
- components/Deck/ContentPanel/ContentActions/ContentActionsHeader.js
- components/Deck/ContentPanel/NoPermissionsModal.js
- components/Deck/TreePanel/TreeNode.js
- components/Deck/TreePanel/TreePanel.js
- stores/DeckTreeStore.js
- stores/PermissionsStore.js
This PR addresses issues SWIK-1134 and SWIK-1200. 
It forbids editing older root deck revisions and shows appropriate modal if someone is an editor and tries to edit a read only revision. For people without edit rights, the modal just informs them about ways to gain edit access. Also, a bug is solved when going back through browser history the no permissions modal appears again.
> Swik 1134 forbid editing old deck revisions

- components/AddDeck/AddDeck.js
Does not yet seem to work with adding an imported deck. Perhaps this is
a localhost problem. testing on experimental.
2017-04-15T18:15:50.189Z - info:  Id=-1, Service=deck.js,
Resource=deck.update, Operation=update, Method=POST
2017-04-15T18:15:50.227Z - error:  Id=-1, Actions=[o], User=kadevgraaf,
filepath=/index.js, statusCode=500, message=Cannot read property 'id'
of undefined, url=/api, method=POST, X-Requested-With=XMLHttpRequest,
Content-Type=application/json, url=/api, timeout=30000
2017-04-15T18:15:53.109Z - error:  Id=-1, Actions=[o, r],
User=kadevgraaf, type=Service Unavailable, description=Server is
currently unable to handle the request., actionRequired=Please try
after some time., statusCode=503, statusText=Service Unavailable,
navStack=o, r
> Add options in adddecks

- components/AddDeck/AddDeck.js
- components/Deck/ContentPanel/DeckModes/DeckEditPanel/DeckPropertiesEditor.js
- components/Deck/ContentPanel/SlideModes/SlideEditPanel/SlideContentEditor.js
- components/Deck/ContentPanel/SlideModes/SlideViewPanel/SlideViewPanel.js
- components/Deck/Presentation/Presentation.js
This PR requires that the SWIK-983 change in the reveal.js submodule also be complete.
Main change is that we don't return white.css as a theme if we have a theme with "default".  The white.css file should only be used for legacy, and default.css should be used for the new themes.
It also adds in all themes for the addDeck component, since they should all be ready for deployment. 
A bug with the display in view and possibly edit mode is highlighted with this change, particularly on e.g., serif, but this existed anyway, and came as a result of changing the .reveal div to position:absolute.  I'll create a separate ticket for that.
> Swik-1123 apply themes to deck themes tester

- components/Deck/ActivityFeedPanel/ActivityFeedPanel.js
- components/Deck/ActivityFeedPanel/ActivityItem.js
- services/activities.js
This fix solves the problem with undefined values in activity-service calls.
Content_kind and content_id are validated before sending a request to the activity-service.
Also, links in ActivityFeedPanel and ActivityItem are modified in case of invalid data.
> Swik 1216 prevent undefined values in activitiesservice calls

- components/Deck/ActivityFeedPanel/ActivityItem.js
This, very small, fix sets the interaction mode of activity feed links to 'view' instead of getting it from the selector.
> SWIK-1228 Fix undefined interaction mode in the activity feed 

- components/AddDeck/AddDeck.js
Added selector.id to the list of parameters. This is required for the top_root_deck parameter in deck.update (deck.js, line 216).
> SWIK-1216 Fixing redirection/deck metadata update after import

- actions/import/uploadFile.js
- components/AddDeck/AddDeck.js
- services/import.js
- stores/ImportStore.js
This branch improves L&F of the import progress bar.
While uploading a file, the progress bar percentage is increased every 2s (reintroducing Kurt's code, with some modifications), until 65%, for the amount which is calculated based on the file size. Since currently we don't have the real information about the file upload progress, this calculation is an estimation and will be more or less accurate depending on the user's network upload speed. If, after reaching 65%, the upload is not yet finished, the message will change from 'Uploading file' to 'Converting file'.
Accessibility is also improved.
> Swik 568 refine progress bar

- components/Deck/ActivityFeedPanel/ActivityFeedPanel.js
- components/Deck/ActivityFeedPanel/ActivityList.js
- components/Deck/Deck.js
- package.json
Fixing Activity feed panel layout. Minor changes - some styles were modified to fix panel width.
Also fixed SWIK-1198 'Activity feed shows only the bottom element after hiding the decktree', by changing ReactList type to 'simple'.
> Swik 1239 fix activity feed width

- stores/ImportStore.js
This is a small fix for the import progress bar. It sets the message 'Converting' to be displayed while waiting for the number of slides (received from the deck-service) to start increasing (meaning that the import-service has created the deck with 1 slide and is in the process of converting the rest of the slides). This is significant when importing larger presentations.
> Swik 1410 fix label of import progress bar

- services/userProfile.js
Languages might be saved in the db as "xx-XX", but the user-service only accepts (due to a recent change) "xx_XX". This PR makes sure that issued data is always in the allowed format and thereof transformes all the database entries to the right format over time. This prevents to execute a migration script on the database (also for testing and stable deployments).
This will fix the error for uploading new user pictures (settings of a user)
> UserLanguage fix

- components/Deck/ContentModulesPanel/ContentDiscussionPanel/AddComment.js
- components/Deck/ContentModulesPanel/ContentDiscussionPanel/ContentDiscussionPanel.js
This is a small bugfix.
It was discovered that a comment is sometimes added to the wrong node. This was due to the invalid selector which was used. This branch fixes this by passing proper selector as a property of the component.
> SWIK-1454 Using selector from props

- components/Deck/ContentModulesPanel/ContentDiscussionPanel/AddComment.js
- components/Deck/ContentModulesPanel/ContentDiscussionPanel/AddReply.js
This is a small fix which allows adding comment (and replies) without the text of the comment. The title field is still required.
Required changes on the discussion-service side are already implemented.
> Swik 1455 unrequire comment text

- components/Deck/TreePanel/TreeNode.js
Buttons in the node toolbar of the treepanel now are well remarked when they are selected.
> Swik 1456 bugfix

- components/Footer/Footer.js
- components/Home/About.js
- components/Home/License.js
- configs/routes.js
This adds a page describing the Creative Common license used in SW. Available at /license 
It also merges the updated footer layout.
> Created license info page, added link to footer; improved layout About page

- components/Deck/ContentPanel/AttachSubdeck/AttachSlidesModal.js
- components/Deck/ContentPanel/AttachSubdeck/AttachSubdeckModal.js
- components/Deck/TreePanel/TreeNode.js
The buttons in the deck tree used the css semantic ui tooltip which
in many cases (e.g. first node) wouldn't show correctly. This commit
rewrites the buttons using the corresponding react semantic ui components
and uses the react semantic popup for the tooltip, which resolves the
issue.
> Fix partially hidden tooltip problem in decktree

- components/Deck/ContentPanel/ContentActions/ContentActionsFooter.js
- components/Deck/ContentPanel/ContentActions/DownloadModal.js
Download button opens a dialog in which users can select the file format to download, and then the user can click on "download"  or on "cancel" to discard the action.
With this new interface, the bug instroduced by the download button is erased.
It also uses intl to translate the sentences, except the name of the formats.
> BugFix: Swik 1599 fix download with a dialog

- package.json
Set image-cropper to a fixed version, as maxWidth crop option has been removed in newer versions of the lib.
> Fix Image Cropper missing option

- actions/activityfeed/addActivities.js
- actions/activityfeed/addActivity.js
- services/activities.js
This completes work related to securing the activities- and xapi-services with jwt and including the email in the jwt token so that it can be safely and efficiently used in the xapi-service to properly write user activities in the learning locker.
> Support sending JWT token when posting user activities

- components/Deck/ContentPanel/SlideModes/SlideEditPanel/SlideContentEditor.js
image upload expects that fileservice runs on same domain, otherwise
different, e.g., Cross-Origin Resource Sharing, method is necessary
> use dynamic domain based on microservice definition

- components/PresentationRoomsHTMLLayout.js
- server/handleServerRendering.js
I've added a custom HTML template for the presentation rooms feature, just like we did for the presentation mode. I've replicated the introduced changes for the presentation mode and removed a lot of unnecessary JS libs and CSS libs, that are not needed for presentation rooms feature. 
This shrinks the size of the application (that initially must be downloaded) and the DOM size a lot. It also decreases initial load time of the page, as the browser does not need to evaluate so much libraries anymore.
Please verify that everything is still displayed correctly (as I removed some CSS libs) and verify that everything still works, without throwing any errors on the browser console (as I removed a lot of JS libs).
> Added a custom HTML template for the presentation rooms feature

- stores/DeckTreeStore.js
this prevents an unexpected error when deleting a node in deck tree
> catch the error of deleting a slide in decktree

- components/Deck/ContentPanel/DeckModes/DeckViewPanel/DeckViewPanel.js
Please test! Comment out translation panel on deckview, added back in old code
> comment out translation panel, reinstate language label

- components/DeckCollection/CollectionPanel/CollectionPanel.js
Fixes issue that one cannot view a deck collection page (eg http://localhost:3000/collection/1?sort=order) when not signed in
> Fix access to collection page when not signed in

- actions/loadDeck.js
This is a small fix that deals with the problem of having empty userid field when creating view activities triggered by guest users.
> SWIK-2080 if not signed in, set userid to 0 when creating an activity

- stores/ActivityFeedStore.js
Activity feed does not update properly when there is a new comment on a deck with id which has no explicit revision number. This a small fix for this issue.
> SWIK-2111 fixing activity feed store update

- docker-compose.yml
- microservices.js.template
I noticed that the platform cannot establish connection with the nlp service on experimental, so I added nlp service to microservices.js.template and the respective env var to docker-compose.yml
> Add nlp to microservices template and SERVICE_URL_NLP to docker-compose

- components/Header/Header.js
Made MediaQuery take into account not the width of the device, but the width of the web page. This fixes the issue with not working Hamburger menu on desktop computers with modern screen resolution.
> SWIK-1982 Show mobile header on any screen where the user menu can't be shown due to the width of the browser

- components/Deck/Presentation/Presentation.js
Removes support for these keyboard bindings because they conflict with screenreaders. Should be done with associated reveal.js PR
> SWIK-2100 removes N and H shortcut

- components/Deck/Presentation/Presentation.js
Removes margin, so the presentation should use full screen.  Associated PR in reveal.js.
NOTE: Overflow is currently set to visible, unlike in slide view. Easy to change to `overflow:hidden` for consistency, depending on what we prefer.
> SWIK-2142 remove margin to use full screen presentation

- components/Deck/ContentPanel/ContentActions/ContentActionsHeader.js
Fix to reduce gap between edit button and content panel.
@kadevgraaf this is caused by the buttons in the right toolbar being made slightly larger when you combine 2 icons. This is a hack but should be fixed properly when we sort out icons. Can you check I haven't broken anything?
> Swik 2154 edit button padding

- components/Deck/ContentPanel/DeckModes/DeckViewPanel/DeckViewPanel.js
This is a partial revert to quickly fix this issue for the release.
Some links when implemented as NavLink don't work correctly,
reverted to using <a> tags.
> Fix deck view panel slide thumbnail links showing deck edit

- components/AddDeck/AddDeck.js
- components/Deck/ContentPanel/DeckModes/DeckEditPanel/DeckPropertiesEditor.js
- components/Deck/ContentPanel/DeckModes/DeckViewPanel/DeckViewPanel.js
This patch will make current master compatible with some language code fixes we have agreed upon: 
- we are going to be using two-character language codes ([ISO-639-1](https://en.wikipedia.org/wiki/ISO_639-1))
- a fix for the existing database data will be applied to the mongodb data using `truncatelangs` command of https://github.com/slidewiki/slidewiki-data-utils
This is a transitional code change that will be refined once the translations PRs are merged: https://github.com/slidewiki/deck-service/pull/136 and https://github.com/slidewiki/slidewiki-platform/pull/899.
This will also allow the deck service PR to be merged, so that we'll be able to properly review / test the platform PR.
> Apply some minor fixes to work with new language codes in deck service

- stores/UserRecommendationsStore.js
There were some changes in the DeckCard component which cause an issue with slideshow links in the RecommendedDecks panel. This very small fix adds slugs to recommended decks to fix this.
> SWIK-2331 Fix slideshow links in Recommended decks panel

- components/AddDeck/AddDeck.js
Import preview currently does not use the selected theme when showing slide thumbnails.
This is a very small fix for this.
> Using the selected theme for import preview thumbnails

- components/Deck/ContentPanel/DeckModes/DeckEditPanel/DeckPropertiesEditor.js
Now editors are displayed with their displayName. Groups detail Modal is already using the new attribute.
> [SWIK-2370_displayName_in_deckeditors]

- services/deck.js
This simply sets up the platform code to read user info from user service instead of deck service. The idea is that if we need something else from the user service, e.g. the new optional displayName, this can be handled on the platform.
> Fetch username from user service in deck featured, recent responses

- components/User/UserProfile/PrivatePublicUserProfile/UserMenu.js
There was a small bug in my implementation of recommended decks functionality which caused 'Owned decks' to be displayed instead of 'My decks' (except on experimental). :( This is a fix for that.
I've changed back the condition for showing 'Owned decks' instead of 'My decks':
if(this.props.user.uname !== this.props.loggedinuser) {   ...
> Fix - showing 'Owned decks' instead of 'My decks' for other users

- components/Deck/ContentModulesPanel/DataSourcePanel/EditDataSource.js
This is a very small fix of a typo which prevented saving the year field when editing datasources.
> SWIK-2429 fixing Publication year removed when edit Sources

- components/Paint/PaintModal.js
Add the handleKeyPress function for opening the Paint Modal from the slide edit left panel.
Previously this function was referenced but did not exist in the code.
> SWIK2439 - Added handleKeyPress function

- components/Deck/ContentModulesPanel/ContentHistoryPanel/ContentChangeItem.js
There is a problem with history tab displaying hex encoded content in some cases (special characters, e.g. Greek letters). This fix for the platform handles existing content, while the fix for new content (created by import) is already on the import-service.
Also, the icon for the remove action was fixed.
> SWIK-2440 Version changes display Hex encoding

- components/Deck/ContentPanel/ContentActions/DownloadModal.js
Commented out option for PDF in the download modal as it is broken. New print view can be saved to PDF
> hot-fix remove pdf option from download modal as broken

- server/handleServerRendering.js
it is for using different layouts based on different keywords used in the req url e.g. presentationIE, print, neo4jguide, etc.. For some of these identifiers, we use a slice of 0,20 from the req url that might become tricky in future if our deck ids get very large...
> increase the URL req slice

- components/Login/LoginModal.js
This PR fixes SWIK-1956.
This bug has existed because of a textarea that is NOT displayed in the LoginModal. Is the textarea needed at all? There is only a description text in the textarea (that isn't displayed in the modal). @abijames Or is needed because of e.g. accessibility reasons?
If not, I'd prefer to remove the textarea.
> SWIK-1956 Fixes error message in browser console on homepage

- components/Header/Header.js
This PR fixes that the header bar is displayed twice on an IPAD (emulation in chrome) and thus having two login modals opened up.
Furthermore I've increased the threshold to jump to the desktop view, as some buttons were not available on the homepage on e.g. an IPAD.
This won't fix the request to use em instead of px, as the framework has no support for em.
@abijames Is it okay to show the mobile bar till 1050 pixels? Before it was set to 768 pixels, but e.g. the login button wasn't displayed on screens that are e.g. 900px wide.
> SWIK-2475 Fixes mobile header bar issues

- components/DeckCollection/Modals/AddDecksModal/AddDecksModal.js
- components/User/UserProfile/PrivatePublicUserProfile/PrivatePublicUserProfile.js
- components/User/UserProfile/PrivatePublicUserProfile/UserDecks.js
This is a very small bug fix, easy to check and merge.
A recent commit has changed
`export function fetchUserDecks(context, payload, done) {`
to 
`export default function fetchUserDecks(context, payload, done) {`
However, there are still
`import { fetchUserDecks }`
in a couple of places and this brakes some things (add decks to playlist, sorting and filtering on 'My decks' page)
> SWIK-2512 Fix fetchUserDecks imports

- components/Deck/ContentModulesPanel/ContentQuestionsPanel/ContentQuestionsPanel.js
Make Download questions button visible only if user has edit permissions.
Stops any user from being able to download the questions.
> SWIK-2543 Change visibility of questions download button

- components/Deck/ContentModulesPanel/ContentModulesPanel.js
Hide the questions button in the content modules panel on slides. 
Questions previously added to slides are able to be edited through the deck level questions tab.
> SWIK-2542 Hide question panel button on slides

- components/Deck/ContentPanel/ContentActions/ContentActionsHeader.js
Fix overlapping buttons in content actions header. This is done by making the buttons smaller when the browser window is small (e.g. for tablet screens)
> Swik 2042 fix button overlap tablet mode

- actions/loadContentModules.js
- actions/loadDeck.js
In this PR, the loadQuestionsCount call (currently executed in loadContentModules) is moved to be executed after loading of edit permission info. Edit permission info is needed because exam questions are not displayed to non-editors.
> SWIK-2584 fix occasional wrong number of questions

- actions/loadDeck.js
- actions/loadDeckView.js
- actions/loadLegacy.js
- actions/translation/loadNodeTranslations.js
- components/Deck/ContentPanel/SlideModes/SlideViewPanel/SlideViewPanel.js
- components/Deck/DeckLandingPage.js
- configs/routes.js
- server/handleServerRendering.js
- services/deck.js
- services/decktree.js
- stores/DeckViewStore.js
- stores/SlideViewStore.js
This mainly fixes the deck not found page for landing and deck view pages.
Related to [SWIK-1737](https://slidewiki.atlassian.net/browse/SWIK-1737) as it fixes one part of it: show an error message, but does not include the part about informing users the deck was removed.
Also fixes [SWIK-2526](https://slidewiki.atlassian.net/browse/SWIK-2526), as well as improving some loading indicators when switching between nodes in deck view.
> Swik 555 fix deck not found handling page

- components/Deck/Presentation/Presentation.js
Fixes a duplicate key error for slides in the presentation mode which caused certain slides to disappear. This happened when the same subdeck was attached multiple times. Now using slide-id + index is used as key, instead of only slide-id. 
Example of slide deck that is attaching the same deck multiple times: http://localhost:3000/deck/5043-1/_/deck/5043-1
> Fix duplicate key error presentation mode

- components/LocaleSwitcher/LocaleSwitcher.js
Use native language names instead of the English language name for header language dropdown
> Swik 2590 use native language name for dropdown

- components/common/SWAutoComplete.js
- components/common/SWAutocompleteShared.js
I have commented out some ES6 code that breaks SlideWiki in Internet Explorer. As far as I have seen, the code is not used by other components.
> Fix IE syntax error problem 

- stores/TranslationStore.js
The caused for some slide decks a 504 error on page load, since an exception was thrown.
E.g. this deck cannot be loaded right now: https://slidewiki.org/deck/584 The page is rendered at the server-side, but because there is an exception, the page stops loading. After 60 seconds a 504 Gateway Time-out error will appear.
> Fix error when language is null

- package.json
The package `intl-locales-supported` breaks SlideWiki because the newer version is not compatible anymore (although it should be!)
This is now fixed by specifying the exact version number.
> Set specific version of intl-locales-supported package

- components/Deck/ContentPanel/ContentActions/ContentActionsFooter.js
- components/Deck/ContentPanel/ContentActions/ContentActionsHeader.js
- components/Deck/ContentPanel/SlideModes/SlideControl.js
The following access-keys have been added in the slide view:
- **Start presentation: Alt + s**  =>  in deck-page(/deck/...)  and slide-page(/slide/...)
- **Edit slide: Alt + w** => in deck-page(/deck/...)  and slide-page(/slide/...)
- **Next slide: Alt + n** => in slide-page(/slide/...)
- **Previous slide: Alt + p** => in slide-page(/slide/...)
They have been checked on Chrome and Firefox.
It should be mentioned that in Firefox, Start presentation shortcut open also history menu.
Fixes #1204
> 1204 - access-keys in slide-view have been added.

- components/Deck/ContentPanel/SlideModes/SlideEditPanel/MarkdownEditor.js
- components/Deck/ContentPanel/SlideModes/SlideViewPanel/SlideContentView.js
Fixes a problem where newly created (unsaved) Markdown slides have a wrong alignment. For example:
_(the text should be vertically aligned in the middle)_
> Fix wrong alignment of unsaved Markdown slides

- components/Deck/ContentModulesPanel/ContentHistoryPanel/ContentChangeItem.js
Solves a problem with an error that occurs when reverting a slide to a previous version. 
When the revert button is clicked, the following error appears:
```
Uncaught TypeError: Cannot read property 'formatMessage' of undefined
at ContentChangeItem.handleRevertClick (ContentChangeItem.js:32)
at apply (_apply.js:15)
at baseInvoke (_baseInvoke.js:21)
at apply (_apply.js:16)
at _overRest.js:32
at Button.js:77
at HTMLUnknownElement.callCallback (react-dom.development.js:188)
at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
at invokeGuardedCallback (react-dom.development.js:292)
at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:306)
```
> fix: solve a problem with reverting slides

- stores/TranslationStore.js
This forked deck is not working because a language translation is empty:
http://slidewiki.org/deck/130268-1/03-rdf-serializations/slide/851750-5/130271-1:7;851750-5:4/
This PR changes the check for null to also check if the property exists at all.
> fix: fork legacy deck without language
